# Generated by Django 5.2 on 2025-09-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet_mask', models.CharField(max_length=15)),
                ('ospf_area', models.CharField(default='0.0.0.0', max_length=20)),
                ('mpls_label', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='4-Router MPLS OSPF Lab', max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Network Topologies',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('router_type', models.CharField(choices=[('PE', 'Provider Edge'), ('P', 'Provider'), ('CE', 'Customer Edge')], default='PE', max_length=2)),
                ('ip_address', models.GenericIPAddressField()),
                ('loopback_ip', models.GenericIPAddressField()),
                ('as_number', models.IntegerField(help_text='Autonomous System Number')),
                ('mpls_enabled', models.BooleanField(default=True)),
                ('ospf_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OSPFConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(default=1)),
                ('ospf_router_id', models.GenericIPAddressField()),
                ('area', models.CharField(default='0.0.0.0', max_length=20)),
                ('network_statements', models.TextField(help_text='JSON array of network statements')),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ospf_config', to='netlab.router')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('ping', 'Ping Test'), ('traceroute', 'Traceroute Test'), ('ospf_neighbors', 'OSPF Neighbor Test'), ('mpls_labels', 'MPLS Label Test'), ('lsp_path', 'LSP Path Test')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='netlab.networktopology')),
                ('source_router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_as_source', to='netlab.router')),
                ('target_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_as_target', to='netlab.router')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.IntegerField(default=1000)),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='netlab.networkinterface')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='netlab.networkinterface')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='netlab.networktopology')),
                ('router_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='netlab.router')),
                ('router_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='netlab.router')),
            ],
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='netlab.router'),
        ),
        migrations.CreateModel(
            name='MPLSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldp_router_id', models.GenericIPAddressField()),
                ('label_range_min', models.IntegerField(default=16)),
                ('label_range_max', models.IntegerField(default=1048575)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpls_config', to='netlab.router')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='networkinterface',
            unique_together={('router', 'interface_name')},
        ),
        migrations.CreateModel(
            name='TopologyRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netlab.router')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='netlab.networktopology')),
            ],
            options={
                'unique_together': {('topology', 'router')},
            },
        ),
    ]
