name: Django CI

on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Hello world check
      run: |
        echo "hello world"
        hostname
        cd /var/www/html/django_demo
        git pull origin main
        hostname
        
  Test:
    runs-on: self-hosted
    steps: 
      - name: this is demo test plan
        run: echo "Hello test job"   

  Deploy: 
    runs-on: self-hosted 
    steps: 
      - name: this is deploy phase
        run: echo "Hello deploy job"

# jobs:
#   build:

#     runs-on: self-hosted
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.7, 3.8, 3.9]

    # steps:
    # - uses: actions/checkout@v4
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py test
